language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -f Dockerfile.dev . -t arch23/docker-react-example

script:
  - docker run -e CI=true arch23/docker-react-example npm run test