language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -f Dockerfile.dev . -t arch23/docker-react-example

script:
  - docker run -e CI=true arch23/docker-react-example npm run test

deploy:
  provider: elasticbeanstalk
  region: "sa-east-1"
  app: "docker-react-example"
  env: "Dockerreactexample-env"
  bucket_name: "elasticbeanstalk-sa-east-1-848044165646"
  bucket_path: "docker-react-example"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY